### ISSUE TITLE
AST nodes need an identity

### ISSUE THREAD

**Issue by benjie** [oguimbal/pgsql-ast-parser#27] opened 2021-02-26 16:57 UTC
Hey Olivier, thanks again for this awesome project and your quick fixes so far!

I've spent a few hours attempting to progress prettier-plugin-pg based on this, and the issue I'm hitting up against is this:

**Given an AST node, I need to know what it is, so that I can output it.**

At the moment the TypeScript types are great for navigating the AST; but when you've fed the AST into something like prettier and it hands you back an AST node it's very hard to tell what you're dealing with. For example `PGComment` and `CommentStatement` both have a `comment` property, so without exhaustively checking the rest of the shape I can't tell which is which (and the code that checks may be invalidated by nodes you add in future).

**Suggested solution**: all nodes should get a `_nodeType` (or similar) entry containing the type of node it is:

```ts
interface PGComment extends PGNode {
  _nodeType: 'PGComment';
  ...
}
interface CommentStatement extend PGNode {
  _nodeType: 'CommentStatement';
  ...
}
```

this makes it very easy to figure out what to do, and even better the TypeScript types should work automatically if you do for example `switch (node._nodeType) { case "PGComment": { ... } }` in the inner code it'll know it's a PGComment.

**Comment by benjie** [comment] 2021-02-26 17:00
(Aside: 4 of the `import`s you use in `to-sql` are not `export`-ed from the package so I cannot use that code as a template.)

**Comment by oguimbal** [comment] 2021-03-02 08:44
FYI, if I used [POSITION] as a symbol property, it's because pg-mem query executor proxies the parsed AST, and check that every property has been read (if not, it means that part of the ast has been ignored, meaning that something supported by the parser is not implemented in the executor => it throws an error).

For that reason, I would tend to do the same with this nodeType (so it's not taken into account by pg-mem exhaustivity check). But maybe it will be a bit heavy to use ? (that exhaustivity check could be adapted to ignore some properties)

**Comment by benjie** [comment] 2021-03-02 09:26
I really like that pattern :+1: 

I think an easier way to address it might be more of a convention, such as "if the key starts with `_` then we can ignore it" - that way we can write the AST out as JSON (which we can't easily do with symbols). So then each node would have `_position` and `_type` and maybe more features in future.

**Comment by benjie** [comment] 2021-03-02 11:22
(If you're not a fan of `_` as a prefix, `$` is also a solid choice.)

**Comment by oguimbal** [comment] 2021-03-07 13:03
Hi !
I ran some experiment to determine wether if adding an identity is easy to implement. It is not obvious (or at least, it has a non trivial impact on parser readability & maintainability).

That said, maybe it would be acceptable to implement it using `astVisitor` ?

```typescript
const IDENTITY = Symbol('identity');
const id = (name: string) => (n: any) => void n[IDENTITY] = name;
const visitor = astVisitor(map => ({
         ref: id('ref'),
         call: id('call'),
         select: id('select'),
         // ...etc...
}))

// then use it like that:
visitor.statement(myStatmentAst);
```

advantages:
- It's not opiniated... menaing that you get to specify which level of detail you want, which AST nodes to tag, etc...
- It is easier to maintain (you will likely have less regressions on you side, since you wont depend from my mistakes)

disadvantages:
- you dont have Typescript type disrimination out of the box.

Tell me what you think

**Comment by benjie** [comment] 2021-03-07 13:40
Interesting approach. Could we have that implemented as a helpful utility in core? I'm worried about it diverging over time as you add more nodes; your exhaustivity checks would be helpful here I think.

I wonder if we could achieve it via meta-programming over the existing TypeScript types, maybe?

**Comment by oguimbal** [comment] 2021-03-07 13:59
Mmmh... That may be doable, yes. I'll look into it.

**Comment by oguimbal** [comment] 2021-03-08 10:43
Could you try this ? Maybe it is sufficient ?

```typescript
export const identityMarker = astMapper(m => {
    return new Proxy({}, {
        get: (_, prop) => {
            return (v: any, ...others: any[]) => {
                v['_type'] = prop;
                return (m.super() as any)[prop](v, ...others);
            };
        }
    });
});


type Arg<T> = T extends (val: infer X) => any ? X : never;
type _Mapped = { [M in keyof IAstPartialMapper]: Arg<IAstPartialMapper[M]> };
type _Marked = {[T in keyof _Mapped]: _Mapped[T] & { _type: T }}
export type PGNodeMarked = _Marked[keyof _Marked] & PGNode;
```


usage:

```typescript
const ast = parse(whatever);
identityMarker.statement(ast);
```

then, you can  use `PGNodeMarked` to discriminate against nodes:

```typescript
let t: PGNodeMarked = ...;
switch (t.type) {
    // strongly typed discriminiation
}
```

**Comment by benjie** [comment] 2021-03-17 10:58
Using via:

```ts
const { comments, ast: rawAst } = parseWithComments(text, { locationTracking: true });
const ast = rawAst.map((statement) => identityMarker.statement(statement));
```

This seems to be working so far; thanks! Will keep investigating.

**Comment by oguimbal** [comment] 2021-03-31 11:12
I guess this is solved for now, so I'm closing this to help tracking, reopen if needed 😊

**Closed by oguimbal** 2021-03-31 11:12 UTC
