### ISSUE TITLE
Library causes crashes in Safari browser due to lack of support for lookbehind regex.

### ISSUE THREAD

**Issue by colbenkharrl** [oguimbal/pgsql-ast-parser#110] opened 2022-08-03 20:23 UTC
Our team has started adopting this library for client-side query validation. We noticed that in Safari browser using this library causes our React application to crash before it has a chance to load due to an invalid regex being used in the lexer:

https://github.com/oguimbal/pgsql-ast-parser/blob/e2cec38142e242ec5e7808fb2bd363b805439639/src/lexer.ts#L49

```
SyntaxError: Invalid regular expression: invalid group specifier name
```
Unfortunately, Safari/WebKit has still not added support for lookbehind assertions in `RegExp`. [Here is the open bug ticket.](https://bugs.webkit.org/show_bug.cgi?id=174931)

I have validated that if we stop importing this library into our application, things function as normal in Safari.

Re-assessing the composition of this regex, which seems to be just looking for `/*`, should resolve this issue.

**Comment by gthb** [comment] 2022-08-09 13:48
Duplicate of https://github.com/oguimbal/pgsql-ast-parser/issues/34

**Comment by oguimbal** [comment] 2022-08-16 08:06
yup, duplicate :)

**Closed by oguimbal** 2022-08-16 08:06 UTC
